### PR TITLE
Windows 7: Manually install SP1, Servicing Stack Update,  Update Rollup & Cumulative Update

### PR DESCRIPTION
**Pull request by qmfrederik**
The current approach for Windows 7 is to apply Windows Updates via `win-updates.ps1` which is triggered by `Autounattend.xml`.

The VM will start downloading and applying updates as they come in, with a maximum of 5 cycles and 500 updates per cycle.

For Windows 7, this approach seems to break down due to the large number of updates available. I left a build running for over 10 hours, and it still hadn't finished.

This PR takes a different approach for Windows 7, by manually installing a couple of well-known updates first, and then reverting to Windows Update. This allows me to build an up-to-date Windows 7 box in about 2 hours.

Long story short, this PR changes the update process so that these updates are installed manually:
1. [KB976932](https://support.microsoft.com/en-us/help/976932/): Windows 7 Service Pack 1,
2. [KB4490628](https://support.microsoft.com/en-us/help/4490628): Windows 7 Servicing Stack Update (March 2019),
3. [KB4474419](https://support.microsoft.com/en-us/help/4474419): Windows 7 SHA-2 Code Signing Support (September 2019) (requires 2),
4. [KB4516655](https://support.microsoft.com/en-us/help/4516655): Windows 7 Servicing Stack Update (September 2019) (requires 3),
5. [KB3125574](https://support.microsoft.com/en-us/help/3125574): Windows 7 Convenience Rollup (2016),
6. [KB4519976](https://support.microsoft.com/en-us/help/4519976): Windows 7 Monthly Rollup (October 2019),
7. .NET Framework 4.8
8. PowerShell 5.1 (requires 7)

These updates already get you a fairly well-patched Windows 7 system, though some security updates are not installed, and it still comes with IE 8.

As a final step, the remaining updates are installed using Ansible.

This PR takes a different approach towards installing updates. Instead of using the `Autounattend.xml` file, they are installed using Packer provisioners. The main reason for doing this was so that there's some console output available when the build is running, which you can use to get an idea of what Packer is doing. This is useful when building on remote build servers.

Because you can't install Windows Updates over a remote PowerShell session (which is what Packer uses to communicate with the VM), I've used Ansible to install them (which will create a scheduled task in Windows to get the updates running).

This departs a bit from the approach used by this repository, so let me know what you think. The main motivation is to get the build time for a Windows 7 box down to something reasonable (i.e. ~2 hours instead of 10+ hours :smile: )

### CODE REVIEW

**Comment by qmfrederik** [comment]
- Pipeline run: https://dev.azure.com/qmfrederik/packer-windows/_build/results?buildId=800&view=logs&j=dae724bc-a4ea-5563-01ef-e58ef100ae6d
- Box built using this template: https://app.vagrantup.com/quamotion/boxes/windows_7/versions/20191022.3

**Comment by StefanScherer** [comment]
The checks on AppVeyor failed. It requires Ansible and maybe other dependencies to be installed on a Windows host.
At least a small HowTo install all the dependencies is required for the README.md.
And I would like to see the tests green (either skip the qemu builder in validation, or better install the dependencies which would proof that it works at least for the validation step).

**Comment by StefanScherer** [comment]
@qmfrederik I'm fine if you skip the windows_7.json entirely at https://github.com/StefanScherer/packer-windows/blob/my/test.ps1#L17

**Comment by StefanScherer** [comment]
Thanks for the contribution. I'll merge this in as is although it is harder for others to build windows 7 images with Ansible.
A quicker build seems reasonable.

**Pull request merged**
