### PR TITLE
Use VirtualBox 6.1 parameter --clipboard-mode

### LINKED ISSUE #240: VirtualBox 6.1 renamed --clipboard to --clipboard-mode
There is no more `--clipboard` in VirtualBox 6.1 - it is now `--clipboard-mode`:

https://www.virtualbox.org/manual/UserManual.html#vboxmanage-cmd-overview

This causes the following to fail: https://github.com/StefanScherer/packer-windows/blob/2020.01.15/vagrantfile-windows_10.template#L25

With this error:

```
==> default: Running 'pre-boot' VM customizations...
A customization command failed:

["modifyvm", :id, "--clipboard", "bidirectional"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "cb2b1fff-eaa6-45a6-8007-c5b488865b1f", "--clipboard", "bidirectional"]
```

Just a heads up - I guess since VirtualBox 6.1 is not supported yet by vagrant this can technically not be considered a bug yet.

### PR DESCRIPTION
**Pull request by StefanScherer**
fixes #240

### CODE REVIEW

**Comment by snowe2010** [comment]
Will this be merged anytime soon?

**Comment by StefanScherer** [comment]
I've updated my machine today and ran a small test for myself. Really looks like this change fixes the issue. Merging now.

**Comment by StefanScherer** [comment]
The next Patch Tuesday builds for app.vagrantup.com should contain the change as well.

**Comment by snowe2010** [comment]
Thanks! Do you know how soon it will be uploaded to Vagrant Cloud? Or should I try to learn how to use packer, since it might take a while?

**Comment by StefanScherer** [comment]
Patch Tuesday is always the second Tuesday in a month. So ping me next week if I forgot to trigger the build :-)

**Comment by snowe2010** [comment]
ah, haha I now understand what you were saying in your original comment. Ok thanks!

**Comment by snowe2010** [comment]
@StefanScherer do you have any instructions for how to build the virtualbox vagrant box? I've tried modifying `build_windows_2019.sh` to be 
```
packer build \
  --only=virtualbox-iso \
  --var vhv_enable=true \
  --var iso_url=~/downloads/17763.379.190312-0539.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso \
  windows_2019.json
```

but am getting lots of errors. and it's also been running for an hour. Not sure how long it should take. If I should email you about this instead of commenting here, let me know.

**Comment by StefanScherer** [comment]
@snowe2010 
The command looks good. The simplest command would be

```
packer build --only=virtualbox-iso windows_2019.json
```

This will download the ISO an build the virtualbox version.
Hm, when it "hangs" during the build it probably has no internet connection for the Windows updates, or the Windows update loop forever (I had that in the past a couple of times).
Either way it would help if you open the VM display and see if there are open windows/terminals with errors, the default is a non-headless build, so it should appear.

**Comment by snowe2010** [comment]
@StefanScherer bump on the build for Vagrant Cloud 😉

**Comment by StefanScherer** [comment]
@snowe2010 Thanks, I already kicked off a build https://circleci.com/gh/StefanScherer/packer-builder/tree/master

**Comment by StefanScherer** [comment]
Turns out that VirtualBox 6.1.4 reverted that change making the latest boxes incompatible again 😅

**Comment by muddman** [comment]
oof -- then i wasted a few hours today repackaging five of your older boxes so I could continue running simultaneous test kitchen tests including both v2020.02.12 and older boxes in virtualbox 6.1.2. :joy:

I'll bet they got an ear full about the change when it broke everyone's CI tests.

```
Instance                      Driver   Provisioner  Verifier  Transport  Last Action    Last Error
py3-windows-10-1909           Vagrant  SaltSolo     Inspec    Winrm      Verified       <None>
py3-windows-10-1903           Vagrant  SaltSolo     Inspec    Winrm      <Not Created>  Kitchen::ShellOut::ShellCommandFailed
py3-windows-10-1809           Vagrant  SaltSolo     Inspec    Winrm      <Not Created>  Kitchen::ShellOut::ShellCommandFailed
py3-windows-10-1803           Vagrant  SaltSolo     Inspec    Winrm      <Not Created>  Kitchen::ShellOut::ShellCommandFailed
py3-windows-10-1709           Vagrant  SaltSolo     Inspec    Winrm      <Not Created>  Kitchen::ShellOut::ShellCommandFailed
py3-windows-server-2019-1809  Vagrant  SaltSolo     Inspec    Winrm      Verified       <None>
py3-windows-server-2016       Vagrant  SaltSolo     Inspec    Winrm      <Not Created>  Kitchen::ShellOut::ShellCommandFailed
```

So you'll be releasing new versions of your 2020.02.12 builds of windows_10 and windows_2019 boxes that will use the original customization setting?

```
- v.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
+ v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
```

BTW -- thank you very, very much for providing packer-windows, all the vagrant boxes on vagrant cloud and for updating them so regularly.  I'm doing the most comprehensive windows testing I've ever done using them.

```
- StefanScherer/windows_10 (v2020.02.12):  Windows 10, version 1909 (OS Build: 18363.657)
- StefanScherer/windows_10 (v2020.01.15):  Windows 10, version 1903 (OS Build: 18362.592)
- StefanScherer/windows_10 (2019.05.15): Windows 10, version 1809 (OS Build: 17763.503)
- StefanScherer/windows_10 (2018.09.12): Windows 10, version 1803 (OS Build: 17134.285)
- StefanScherer/windows_10 (2018.03.14): Windows 10, version 1709 (OS Build: 16299.309)
- StefanScherer/windows_2016 (2019.02.14): Windows Server 2016, version 1607 (OS Build: 14393.2791)
- StefanScherer/windows_2019 (2020.02.12): Windows Server 2019, version 1809 (OS Build: 17763.864)
```

**Comment by StefanScherer** [comment]
@muddman new virtualbox boxes are uploaded to Vagrant Cloud to support 6.1.4

**Comment by snowe2010** [comment]
that's pretty frustrating. thanks for the hard work!

**Pull request merged**
