### PR TITLE
Closed #68 Changed hardware version to 12

### LINKED ISSUE #68: vmware-iso builder (hardware) version:11 vs VMware Fusion 8 (and higher) Workstation 11 (and higher)
I use VMware Fusion 8, Fusion 10, Workstation 12, Workstation 14 for generating my packer images. All of the above release complain about the hardware compatibility version number and request I upgrade it.

https://kb.vmware.com/s/article/1010675
https://kb.vmware.com/s/article/1014006

VMware Fusion 7.x, hardware version 11, 
Latest maintenance release 7.1.3, Nov 12, 2015, newest operating system OS X El Capitan (10.11)

VMware Workstation 11.x, hardware version 11,
Latest maintenance release 11.1.2, Jun 15, 2016, newest operating system Windows 10

Can we increment the version to at least 12?

I'll make a PR if this is approved.

### PR DESCRIPTION
**Pull request by basictheprogram**

### CODE REVIEW

**Comment by StefanScherer** [comment]
Could you update the other *.json templates that also have version 11 inside?
It's better to have them all at the same level.

**Comment by basictheprogram** [comment]
I do not have the ability to test all the *.json templates, ok with PR without testing it?

**Comment by StefanScherer** [comment]
That is ok, I'll build some insider machines in the next days and I can check.
Normally newer guests also need higher HW version. Thanks for mentioning that there is HW version 14, if we have to increase more.

**Comment by StefanScherer** [comment]
Thanks. LGTM.

**Pull request merged**
